#database config
spring:
  datasource:
#    url: jdbc:mysql://192.168.56.105:3306/review?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&MVCC=true
    url: jdbc:mysql://192.168.5.200:3306/review?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&MVCC=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

server:
  servlet:
    context-path: /api
logging:
#  config: classpath:log4j2.xml
  config: classpath:log4j2.yml
  level:
#    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  header: Authorization
  secret_key: fioafgijsdgjsdofg@@Asfjogsrg_SD%)$$3w46)S%6s59slkth)S)Eq254_
  expired_time: 60
