#database config
spring:
  datasource:
    url: jdbc:mysql://192.168.56.105:3306/review?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&MVCC=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace